/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rasyi
 */


public class konversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form konversiSuhu
     */
    public konversiSuhu() {
        initComponents();
        
        java.awt.event.ItemListener listener = evt -> {
        if (autoConvert && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            konversiSuhu();
        }
    };
    r1.addItemListener(listener);
    r2.addItemListener(listener);
    r3.addItemListener(listener);
    r4.addItemListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtsuhu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txthasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("KONVERSI SUHU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Masukkan Suhu Dalam");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius(°C)", "Reamur(°R)", "Fahrenheit(°H)", "Kelvin(°K)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        txtsuhu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsuhu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsuhuFocusLost(evt);
            }
        });
        txtsuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsuhuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsuhuKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Konversi Ke Dalam ");

        buttonGroup1.add(r1);
        r1.setText("Fahrenheit");

        buttonGroup1.add(r2);
        r2.setText("Celcius");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(r3);
        r3.setText("kelvin");

        buttonGroup1.add(r4);
        r4.setText("Reamur");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Cek Hasil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txthasil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthasilActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("°");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r2)
                                    .addComponent(r1))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r4)
                                    .addComponent(r3))))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(163, 163, 163))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2)
                    .addComponent(r3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r4))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(txthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private boolean autoConvert = false;
    private String satuanAktif = "°C";


    private void konversiSuhu() {
        if (txtsuhu.getText().isEmpty()) {
//        javax.swing.JOptionPane.showMessageDialog(this, "Masukkan nilai suhu terlebih dahulu!");
        return;
    }
         try {
        // 2. Ambil nilai suhu dan satuan awal
        // Hapus simbol derajat agar bisa dibaca sebagai angka
        String inputText = txtsuhu.getText().replaceAll("[^0-9.-]", "");
        double suhuAwal = Double.parseDouble(inputText);

        String satuanAwal = jComboBox1.getSelectedItem().toString();
        String satuan = "";

        // 3. Tentukan satuan tujuan berdasarkan radio button
        String satuanTujuan = "";
        if (r1.isSelected()) {
            satuanTujuan = "Fahrenheit";
            satuan = "°F";
        } else if (r2.isSelected()) {
            satuanTujuan = "Celcius";
            satuan = "°C";
        } else if (r3.isSelected()) {
            satuanTujuan = "Kelvin";
            satuan = "°K";
        } else if (r4.isSelected()) {
            satuanTujuan = "Reamur";
            satuan = "°R";
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih satuan suhu tujuan terlebih dahulu!");
            return;
        }

        // 4. Proses konversi
        double hasil = 0;
        switch (satuanAwal) {
            case "Celcius(°C)" -> {
                switch (satuanTujuan) {
                    case "Fahrenheit" -> hasil = (suhuAwal * 9 / 5) + 32;
                    case "Reamur" -> hasil = suhuAwal * 4 / 5;
                    case "Kelvin" -> hasil = suhuAwal + 273.15;
                    case "Celcius" -> hasil = suhuAwal;
                }
            }
            case "Reamur(°R)" -> {
                switch (satuanTujuan) {
                    case "Celcius" -> hasil = suhuAwal * 5 / 4;
                    case "Fahrenheit" -> hasil = (suhuAwal * 9 / 4) + 32;
                    case "Kelvin" -> hasil = (suhuAwal * 5 / 4) + 273.15;
                    case "Reamur" -> hasil = suhuAwal;
                }
            }
            case "Fahrenheit(°H)" -> {
                switch (satuanTujuan) {
                    case "Celcius" -> hasil = (suhuAwal - 32) * 5 / 9;
                    case "Reamur" -> hasil = (suhuAwal - 32) * 4 / 9;
                    case "Kelvin" -> hasil = (suhuAwal + 459.67) * 5 / 9;
                    case "Fahrenheit" -> hasil = suhuAwal;
                }
            }
            case "Kelvin(°K)" -> {
                switch (satuanTujuan) {
                    case "Celcius" -> hasil = suhuAwal - 273.15;
                    case "Reamur" -> hasil = (suhuAwal - 273.15) * 4 / 5;
                    case "Fahrenheit" -> hasil = (suhuAwal - 273.15) * 9 / 5 + 32;
                    case "Kelvin" -> hasil = suhuAwal;
                }
            }
        }

        // 5. Tampilkan hasil di TextField
        txthasil.setText(String.format("%.2f °%s", hasil, satuanTujuan.charAt(0) ,satuan));

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Input harus berupa angka yang valid!");
    }
    }
    
    private void updateInputText() {
    String teks = txtsuhu.getText();

    // Hapus simbol lama (jika ada)
    teks = teks.replaceAll("\\s*°[A-Z]", "").trim();

    // Tambahkan satuan baru
    if (!teks.isEmpty()) {
        txtsuhu.setText(teks + " " + satuanAktif);
    }
}

    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    String pilihan = jComboBox1.getSelectedItem().toString();
    
    // Tentukan simbol derajat sesuai pilihan
    switch (pilihan) {
        case "Celcius(°C)" -> satuanAktif = "°C";
        case "Reamur(°R)" -> satuanAktif = "°R";
        case "Fahrenheit(°H)" -> satuanAktif = "°F";
        case "Kelvin(°K)" -> satuanAktif = "°K";
    }

    // Perbarui tampilan input agar ada derajat
    updateInputText();

    // Jika mode auto aktif, konversi juga langsung dijalankan
    if (autoConvert) {
        konversiSuhu();
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        autoConvert = true;
        konversiSuhu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuhuKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_txtsuhuKeyTyped

    private void txtsuhuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuhuKeyReleased
        // TODO add your handling code here:
    String teks = txtsuhu.getText().replaceAll("\\s*°[A-Z]", "").trim();

    // Jika user mengetik angka, tambahkan derajat otomatis
    if (!teks.isEmpty()) {
        txtsuhu.setText(teks + " " + satuanAktif);
        txtsuhu.setCaretPosition(teks.length()); // kursor tetap di akhir angka
    }

    // Jalankan konversi otomatis
    if (autoConvert) {
        konversiSuhu();
    }
    }//GEN-LAST:event_txtsuhuKeyReleased

    private void txtsuhuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsuhuFocusLost

    }//GEN-LAST:event_txtsuhuFocusLost

    private void txthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JTextField txthasil;
    private javax.swing.JTextField txtsuhu;
    // End of variables declaration//GEN-END:variables
}
