/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rasyi
 */


public class konversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form konversiSuhu
     */
    public konversiSuhu() {
        initComponents();
        
        java.awt.event.ItemListener listener = evt -> {
        if (autoConvert && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            konversiSuhu();
        }
    };
    r1Fahrenheit.addItemListener(listener);
    r2Celcius.addItemListener(listener);
    r3Kelvin.addItemListener(listener);
    r4Reamur.addItemListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbmSatuan = new javax.swing.JComboBox<>();
        txtsuhu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        r1Fahrenheit = new javax.swing.JRadioButton();
        r2Celcius = new javax.swing.JRadioButton();
        r3Kelvin = new javax.swing.JRadioButton();
        r4Reamur = new javax.swing.JRadioButton();
        btnHasil = new javax.swing.JButton();
        txtHasil = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Masukkan Suhu Dalam");

        cbmSatuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius(°C)", "Reamur(°R)", "Fahrenheit(°H)", "Kelvin(°K)" }));
        cbmSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmSatuanActionPerformed(evt);
            }
        });

        txtsuhu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsuhu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsuhu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsuhuFocusLost(evt);
            }
        });
        txtsuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsuhuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsuhuKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Konversi Ke Dalam ");

        buttonGroup1.add(r1Fahrenheit);
        r1Fahrenheit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r1Fahrenheit.setForeground(java.awt.Color.white);
        r1Fahrenheit.setText("Fahrenheit");

        buttonGroup1.add(r2Celcius);
        r2Celcius.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r2Celcius.setForeground(java.awt.Color.white);
        r2Celcius.setText("Celcius");
        r2Celcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2CelciusActionPerformed(evt);
            }
        });

        buttonGroup1.add(r3Kelvin);
        r3Kelvin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r3Kelvin.setForeground(java.awt.Color.white);
        r3Kelvin.setText("kelvin");

        buttonGroup1.add(r4Reamur);
        r4Reamur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        r4Reamur.setForeground(java.awt.Color.white);
        r4Reamur.setText("Reamur");

        btnHasil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHasil.setText("Cek Hasil");
        btnHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasilActionPerformed(evt);
            }
        });

        txtHasil.setEditable(false);
        txtHasil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtHasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHasilActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));

        judul.setBackground(new java.awt.Color(0, 0, 0));
        judul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 0));
        judul.setText("APLIKASI KONVERSI SUHU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cbmSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r2Celcius)
                            .addComponent(r1Fahrenheit))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(r4Reamur)
                            .addComponent(r3Kelvin)))
                    .addComponent(btnHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtHasil))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbmSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2Celcius)
                    .addComponent(r3Kelvin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1Fahrenheit)
                    .addComponent(r4Reamur))
                .addGap(18, 18, 18)
                .addComponent(btnHasil)
                .addGap(18, 18, 18)
                .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private boolean autoConvert = false;
    private String satuanAktif = "°C";


    private void konversiSuhu() {

         try {
        // 2. Ambil nilai suhu dan satuan awal
        // Hapus simbol derajat agar bisa dibaca sebagai angka
        String inputText = txtsuhu.getText().replaceAll("[^0-9.-]", "");
        double suhuAwal = Double.parseDouble(inputText);

        String satuanAwal = cbmSatuan.getSelectedItem().toString();
        String satuan = "";

        // 3. Tentukan satuan tujuan berdasarkan radio button
        String satuanTujuan = "";
        if (r1Fahrenheit.isSelected()) {
            satuanTujuan = "Fahrenheit";
            satuan = "°F";
        } else if (r2Celcius.isSelected()) {
            satuanTujuan = "Celcius";
            satuan = "°C";
        } else if (r3Kelvin.isSelected()) {
            satuanTujuan = "Kelvin";
            satuan = "°K";
        } else if (r4Reamur.isSelected()) {
            satuanTujuan = "Reamur";
            satuan = "°R";
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Pilih satuan suhu tujuan terlebih dahulu!");
            return;
        }

        // 4. Proses konversi
        double hasil = 0;
        switch (satuanAwal) {
            case "Celcius(°C)" -> {
                switch (satuanTujuan) {
                    case "Fahrenheit" -> hasil = (suhuAwal * 9 / 5) + 32;
                    case "Reamur" -> hasil = suhuAwal * 4 / 5;
                    case "Kelvin" -> hasil = suhuAwal + 273.15;
                    case "Celcius" -> hasil = suhuAwal;
                }
            }
            case "Reamur(°R)" -> {
                switch (satuanTujuan) {
                    case "Celcius" -> hasil = suhuAwal * 5 / 4;
                    case "Fahrenheit" -> hasil = (suhuAwal * 9 / 4) + 32;
                    case "Kelvin" -> hasil = (suhuAwal * 5 / 4) + 273.15;
                    case "Reamur" -> hasil = suhuAwal;
                }
            }
            case "Fahrenheit(°H)" -> {
                switch (satuanTujuan) {
                    case "Celcius" -> hasil = (suhuAwal - 32) * 5 / 9;
                    case "Reamur" -> hasil = (suhuAwal - 32) * 4 / 9;
                    case "Kelvin" -> hasil = (suhuAwal + 459.67) * 5 / 9;
                    case "Fahrenheit" -> hasil = suhuAwal;
                }
            }
            case "Kelvin(°K)" -> {
                switch (satuanTujuan) {
                    case "Celcius" -> hasil = suhuAwal - 273.15;
                    case "Reamur" -> hasil = (suhuAwal - 273.15) * 4 / 5;
                    case "Fahrenheit" -> hasil = (suhuAwal - 273.15) * 9 / 5 + 32;
                    case "Kelvin" -> hasil = suhuAwal;
                }
            }
        }

        // 5. Tampilkan hasil di TextField
        txtHasil.setText(String.format("%.2f °%s", hasil, satuanTujuan.charAt(0) ,satuan));

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Input harus berupa angka yang valid!");
    }
    }
    
    private void updateInputText() {
    String teks = txtsuhu.getText();

    // Hapus simbol lama (jika ada)
    teks = teks.replaceAll("\\s*°[A-Z]", "").trim();

    // Tambahkan satuan baru
    if (!teks.isEmpty()) {
        txtsuhu.setText(teks + " " + satuanAktif);
    }
}

    
    private void cbmSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmSatuanActionPerformed
        // TODO add your handling code here:
    String pilihan = cbmSatuan.getSelectedItem().toString();
    
    // Tentukan simbol derajat sesuai pilihan
    switch (pilihan) {
        case "Celcius(°C)" -> satuanAktif = "°C";
        case "Reamur(°R)" -> satuanAktif = "°R";
        case "Fahrenheit(°H)" -> satuanAktif = "°F";
        case "Kelvin(°K)" -> satuanAktif = "°K";
    }

    // Perbarui tampilan input agar ada derajat
    updateInputText();

    // Jika mode auto aktif, konversi juga langsung dijalankan
    if (autoConvert) {
        konversiSuhu();
    }
    }//GEN-LAST:event_cbmSatuanActionPerformed

    private void r2CelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2CelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2CelciusActionPerformed

    private void btnHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasilActionPerformed
        // TODO add your handling code here:
        if (txtsuhu.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Masukkan nilai suhu terlebih dahulu!");
        return;
    }
                
        autoConvert = true;
        konversiSuhu();
    }//GEN-LAST:event_btnHasilActionPerformed

    private void txtsuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuhuKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '-') {
            evt.consume();
        }
    }//GEN-LAST:event_txtsuhuKeyTyped

    private void txtsuhuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuhuKeyReleased
        // TODO add your handling code here:
    String teks = txtsuhu.getText().replaceAll("\\s*°[A-Z]", "").trim();

    // Jika user mengetik angka, tambahkan derajat otomatis
    if (!teks.isEmpty()) {
        txtsuhu.setText(teks + " " + satuanAktif);
        txtsuhu.setCaretPosition(teks.length()); // kursor tetap di akhir angka
    }

    // Jalankan konversi otomatis
    if (autoConvert) {
        konversiSuhu();
    }
    }//GEN-LAST:event_txtsuhuKeyReleased

    private void txtsuhuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsuhuFocusLost

    }//GEN-LAST:event_txtsuhuFocusLost

    private void txtHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHasil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbmSatuan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel judul;
    private javax.swing.JRadioButton r1Fahrenheit;
    private javax.swing.JRadioButton r2Celcius;
    private javax.swing.JRadioButton r3Kelvin;
    private javax.swing.JRadioButton r4Reamur;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtsuhu;
    // End of variables declaration//GEN-END:variables
}
